# Reproducibility for the multimodal retrieval / eval engagement.
# Every number cited in the README is regenerated by these targets from scratch.
#
# Quick start (fresh machine):
#   make venv && make data && make reproduce && make manifest
#
# Eval/retrieval work uses a dedicated venv (.venv-eval, Python 3.11/3.12) so the
# heavy Torch/CLIP deps stay out of the lightweight app/CI environment.

PY  := .venv-eval/bin/python
PIP := .venv-eval/bin/pip

.DEFAULT_GOAL := help

.PHONY: help venv dev-deps data eval ablation faithfulness backbone-sweep \
        reproduce manifest test lint load-test k8s-demo k8s-clean clean

help:  ## List available targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

venv:  ## Create .venv-eval (py3.12) and install the eval/retrieval deps
	python3 -m venv .venv-eval
	$(PIP) install -q -U pip wheel
	$(PIP) install -q -r requirements_eval.txt
	@echo "venv ready: $(PY)"

dev-deps:  ## Install lint/type tooling into the eval venv (black, ruff, mypy)
	$(PIP) install -q black ruff mypy

data:  ## Download + prepare Flickr30k (1K gallery + eval queries)
	$(PY) -m eval.datasets.prepare_flickr30k

eval:  ## Headline: OpenCLIP ViT-H/14, standard 5k protocol -> Recall@5
	$(PY) -m eval.evaluate --retrievers openclip --queries 5k --tag phase3b_headline

ablation:  ## Honest ablation: dense vs +RRF vs +cross-encoder rerank
	$(PY) -m eval.ablation_rerank --rerank-n 50

faithfulness:  ## Prove the vector DB preserves rankings (Qdrant == numpy)
	$(PY) -m eval.faithfulness_check

backbone-sweep:  ## Backbone curve (B/32 -> L/14 -> H/14): the source of the lift
	$(PY) -m eval.backbone_sweep

reproduce: eval ablation faithfulness  ## Regenerate the core eval artifacts
	@echo "Core eval artifacts regenerated under eval/results/"

manifest:  ## Write results_manifest.json (provenance for every cited number)
	$(PY) -m scripts.make_manifest

test:  ## Run the unit/integration test suite (mock mode, no API cost)
	USE_MOCK=true $(PY) -m pytest tests/ -q

lint:  ## Check formatting + lint + types (black, ruff, mypy) — mirrors CI
	$(PY) -m black --check --line-length 100 src/ tests/ eval/ scripts/
	$(PY) -m ruff check src/ tests/ eval/ scripts/
	$(PY) -m mypy --ignore-missing-imports --follow-imports=silent eval/ \
		src/rag/fusion.py src/rag/sparse_retriever.py src/rag/reranker.py \
		src/rag/openclip_retriever.py src/rag/image_search_service.py src/rag/vector_store.py

load-test:  ## Locust load test (start the API first: USE_MOCK=true uvicorn ... :8000)
	$(PY) -m locust -f tests/load/locustfile.py --host http://localhost:8000 \
		--headless -u 500 -r 100 -t 30s --csv tests/load/results/locust500

k8s-demo:  ## Local kind cluster + HPA autoscaling demo: deploy -> Locust load -> observe 2->N->2
	@# caffeinate (macOS) keeps the machine awake so the timed sampling isn't corrupted by sleep
	@command -v caffeinate >/dev/null 2>&1 && caffeinate -i bash scripts/k8s_demo.sh || bash scripts/k8s_demo.sh

k8s-clean:  ## Delete the kind demo cluster
	kind delete cluster --name rag-demo

clean:  ## Remove generated caches (keeps committed eval/results/*.json|md)
	rm -f data/flickr30k/*_gallery.pkl
	rm -rf data/flickr30k/qdrant
	@echo "Cleaned local caches (gallery pickles + local Qdrant store)."
